%YAML:1.0
#cautious: NO TABS!!!!!!!
SERVER_CONFIG:
    HOST: 192.168.11.27
    PORT: 8080

CAMERA_CONFIG:
    CAMERA_INDEX: 0
    WIDTH: 640
    HEIGHT: 480
    FOCAL_LENGTH: [804.6519, 805.4267]
    PRINCIPLE_POINT: [660.5782, 354.5914]
    RADIAL_DISTORTION: [-0.3942, 0.0967]

CLIENT_CONFIG:
    STREAMING: true
    STREAMING_FREQ: 30
    VIDEO_RECORDING: false
    VIDEO_RECORDING_FILE_PATH: ../video/
